import os

from ..model.configuration import Configuration


def install_subcommand(sub_argparser):
    cmd_parser = sub_argparser.add_parser(
        "dumpconfig",
        handler=handle_dumpconfig,
        help="Dump yaml configuration generated by ytt"
    )


def handle_dumpconfig(args):
    config = Configuration(use_config_cache=args.config_cache)
    with open(os.path.join(config.orchestra_dotdir, "config_cache.yml")) as f:
        print(f.read())
